
package com.ejb3.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldJAXWSService", targetNamespace = "http://webservice.ejb3.com/", wsdlLocation = "http://samuli:8080/HelloWorldJAXWSService/HelloWorldJAXWS?WSDL")
public class HelloWorldJAXWSService
    extends Service
{

    private final static URL HELLOWORLDJAXWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDJAXWSSERVICE_EXCEPTION;
    private final static QName HELLOWORLDJAXWSSERVICE_QNAME = new QName("http://webservice.ejb3.com/", "HelloWorldJAXWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://samuli:8080/HelloWorldJAXWSService/HelloWorldJAXWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDJAXWSSERVICE_WSDL_LOCATION = url;
        HELLOWORLDJAXWSSERVICE_EXCEPTION = e;
    }

    public HelloWorldJAXWSService() {
        super(__getWsdlLocation(), HELLOWORLDJAXWSSERVICE_QNAME);
    }

    public HelloWorldJAXWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLDJAXWSSERVICE_QNAME, features);
    }

    public HelloWorldJAXWSService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDJAXWSSERVICE_QNAME);
    }

    public HelloWorldJAXWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLDJAXWSSERVICE_QNAME, features);
    }

    public HelloWorldJAXWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldJAXWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorldJAXWS
     */
    @WebEndpoint(name = "HelloWorldJAXWSPort")
    public HelloWorldJAXWS getHelloWorldJAXWSPort() {
        return super.getPort(new QName("http://webservice.ejb3.com/", "HelloWorldJAXWSPort"), HelloWorldJAXWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldJAXWS
     */
    @WebEndpoint(name = "HelloWorldJAXWSPort")
    public HelloWorldJAXWS getHelloWorldJAXWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.ejb3.com/", "HelloWorldJAXWSPort"), HelloWorldJAXWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDJAXWSSERVICE_EXCEPTION!= null) {
            throw HELLOWORLDJAXWSSERVICE_EXCEPTION;
        }
        return HELLOWORLDJAXWSSERVICE_WSDL_LOCATION;
    }

}
