
package com.ejb3.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldJAXWS", targetNamespace = "http://webservice.ejb3.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldJAXWS {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.SayHelloResponse")
    @Action(input = "http://webservice.ejb3.com/HelloWorldJAXWS/sayHelloRequest", output = "http://webservice.ejb3.com/HelloWorldJAXWS/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @return
     *     returns java.util.List<com.ejb3.webservice.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooks", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.GetBooks")
    @ResponseWrapper(localName = "getBooksResponse", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.GetBooksResponse")
    @Action(input = "http://webservice.ejb3.com/HelloWorldJAXWS/getBooksRequest", output = "http://webservice.ejb3.com/HelloWorldJAXWS/getBooksResponse")
    public List<Book> getBooks();

    /**
     * 
     * @param book
     * @return
     *     returns com.ejb3.webservice.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBook", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.CreateBook")
    @ResponseWrapper(localName = "createBookResponse", targetNamespace = "http://webservice.ejb3.com/", className = "com.ejb3.webservice.CreateBookResponse")
    @Action(input = "http://webservice.ejb3.com/HelloWorldJAXWS/createBookRequest", output = "http://webservice.ejb3.com/HelloWorldJAXWS/createBookResponse")
    public Book createBook(
        @WebParam(name = "book", targetNamespace = "")
        Book book);

}
